language: d
install:
  - git clone https://github.com/martine/ninja.git
  - cd ninja
  - ./configure.py --bootstrap
  - cd ..
  - mkdir bin
  - cp ninja/ninja bin
  - export PATH=$PATH:$PWD/bin
  - gem install cucumber rspec aruba
script:
 - make test
