language: d
d: dmd-2.067.0
before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update
install:
  - sudo apt-get install ninja-build
  - gem install cucumber rspec aruba
script:
  - ./bootstrap.sh make
  - bin/ut
  - cucumber
