language: d
d: dmd-2.067.0
install:
  - gem install cucumber rspec aruba
  - git clone https://github.com/martine/ninja.git
  - cd ninja
  - ./configure.py --bootstrap
  - sudo cp ninja /usr/bin
  - cd ..
  - dub fetch unit-threaded --version=0.4.10
  - dub fetch cerealed --version=0.5.4

script:
  - ./bootstrap.sh make
  - bin/ut
  - cucumber --tags ~@tup
