language: d
install:
  - sudo apt-get update
  - sudo apt-get install ninja-build
  - git clone https://github.com/martine/ninja.git
  - cd ninja
  - ./configure.py --bootstrap
  - cd ..
  - mkdir bin
  - cp ninja/ninja bin
  - gem install cucumber rspec aruba
script:
 - make test
